SAMPLE_WORDS = [
    {"word": "apple", "meaning": "苹果", "phonetic": "/ˈæpl/", "example": "I eat an apple every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "book", "meaning": "书", "phonetic": "/bʊk/", "example": "This is a good book.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "cat", "meaning": "猫", "phonetic": "/kæt/", "example": "The cat is sleeping.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "dog", "meaning": "狗", "phonetic": "/dɒɡ/", "example": "I have a pet dog.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "egg", "meaning": "鸡蛋", "phonetic": "/eɡ/", "example": "I had an egg for breakfast.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "fish", "meaning": "鱼", "phonetic": "/fɪʃ/", "example": "The fish swims in water.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "girl", "meaning": "女孩", "phonetic": "/ɡɜːl/", "example": "She is a happy girl.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "hand", "meaning": "手", "phonetic": "/hænd/", "example": "Wash your hands before eating.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "ice", "meaning": "冰", "phonetic": "/aɪs/", "example": "The ice is cold.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "jump", "meaning": "跳", "phonetic": "/dʒʌmp/", "example": "The rabbit can jump high.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "kind", "meaning": "友善的", "phonetic": "/kaɪnd/", "example": "She is a kind person.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "love", "meaning": "爱", "phonetic": "/lʌv/", "example": "I love my family.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "milk", "meaning": "牛奶", "phonetic": "/mɪlk/", "example": "Drink milk every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "name", "meaning": "名字", "phonetic": "/neɪm/", "example": "What is your name?", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "orange", "meaning": "橙子", "phonetic": "/ˈɒrɪndʒ/", "example": "The orange is sweet.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "play", "meaning": "玩", "phonetic": "/pleɪ/", "example": "Children like to play.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "queen", "meaning": "女王", "phonetic": "/kwiːn/", "example": "The queen lives in a castle.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "rain", "meaning": "雨", "phonetic": "/reɪn/", "example": "It is raining outside.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "sun", "meaning": "太阳", "phonetic": "/sʌn/", "example": "The sun is shining.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "tree", "meaning": "树", "phonetic": "/triː/", "example": "The tree is tall.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "umbrella", "meaning": "雨伞", "phonetic": "/ʌmˈbrelə/", "example": "Take an umbrella with you.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "vegetable", "meaning": "蔬菜", "phonetic": "/ˈvedʒtəbl/", "example": "Eat more vegetables.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "water", "meaning": "水", "phonetic": "/ˈwɔːtər/", "example": "Drink more water.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "yellow", "meaning": "黄色", "phonetic": "/ˈjeləʊ/", "example": "The banana is yellow.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "zebra", "meaning": "斑马", "phonetic": "/ˈzebrə/", "example": "The zebra has stripes.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "apple", "meaning": "苹果", "phonetic": "/ˈæpl/", "example": "I eat an apple every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "banana", "meaning": "香蕉", "phonetic": "/bəˈnænə/", "example": "Bananas are yellow.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "carrot", "meaning": "胡萝卜", "phonetic": "/ˈkærət/", "example": "Carrots are good for eyes.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "duck", "meaning": "鸭子", "phonetic": "/dʌk/", "example": "The duck swims in the pond.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "elephant", "meaning": "大象", "phonetic": "/ˈelɪfənt/", "example": "Elephants have trunks.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "frog", "meaning": "青蛙", "phonetic": "/frɒɡ/", "example": "The frog jumps into the water.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "giraffe", "meaning": "长颈鹿", "phonetic": "/dʒəˈrɑːf/", "example": "Giraffes have long necks.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "hippo", "meaning": "河马", "phonetic": "/ˈhɪpəʊ/", "example": "Hippos live in rivers.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "iguana", "meaning": "鬣蜥", "phonetic": "/ɪˈɡwɑːnə/", "example": "The iguana is green.", "level": 1, "frequency": 2, "difficulty": 2},
    {"word": "jungle", "meaning": "丛林", "phonetic": "/ˈdʒʌŋɡl/", "example": "Many animals live in the jungle.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "kangaroo", "meaning": "袋鼠", "phonetic": "/ˌkæŋɡəˈruː/", "example": "Kangaroos hop on two legs.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "lion", "meaning": "狮子", "phonetic": "/ˈlaɪən/", "example": "The lion is the king of the jungle.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "monkey", "meaning": "猴子", "phonetic": "/ˈmʌŋki/", "example": "Monkeys like to climb trees.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "notebook", "meaning": "笔记本", "phonetic": "/ˈnəʊtbʊk/", "example": "I write in my notebook.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "owl", "meaning": "猫头鹰", "phonetic": "/aʊl/", "example": "Owls hunt at night.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "penguin", "meaning": "企鹅", "phonetic": "/ˈpeŋɡwɪn/", "example": "Penguins live in cold places.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "quilt", "meaning": "被子", "phonetic": "/kwɪlt/", "example": "The quilt is warm.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "rabbit", "meaning": "兔子", "phonetic": "/ˈræbɪt/", "example": "Rabbits have long ears.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "snake", "meaning": "蛇", "phonetic": "/sneɪk/", "example": "Snakes can be dangerous.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "turtle", "meaning": "乌龟", "phonetic": "/ˈtɜːtl/", "example": "Turtles move slowly.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "unicorn", "meaning": "独角兽", "phonetic": "/ˈjuːnɪkɔːn/", "example": "Unicorns are mythical creatures.", "level": 1, "frequency": 2, "difficulty": 2},
    {"word": "ball", "meaning": "球", "phonetic": "/bɔːl/", "example": "Let's play ball.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "cake", "meaning": "蛋糕", "phonetic": "/keɪk/", "example": "Happy birthday! Have some cake.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "desk", "meaning": "书桌", "phonetic": "/desk/", "example": "Put your books on the desk.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "elephant", "meaning": "大象", "phonetic": "/ˈelɪfənt/", "example": "The elephant is very big.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "flower", "meaning": "花", "phonetic": "/ˈflaʊər/", "example": "The flower is beautiful.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "green", "meaning": "绿色", "phonetic": "/ɡriːn/", "example": "The grass is green.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "happy", "meaning": "快乐的", "phonetic": "/ˈhæpi/", "example": "I am very happy today.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "island", "meaning": "岛屿", "phonetic": "/ˈaɪlənd/", "example": "We visited a beautiful island.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "juice", "meaning": "果汁", "phonetic": "/dʒuːs/", "example": "I like orange juice.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "kite", "meaning": "风筝", "phonetic": "/kaɪt/", "example": "Let's fly a kite.", "level": 1, "frequency": 3, "difficulty": 1},
    {"word": "library", "meaning": "图书馆", "phonetic": "/ˈlaɪbrəri/", "example": "I study in the library.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "mother", "meaning": "妈妈", "phonetic": "/ˈmʌðər/", "example": "My mother is kind.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "notebook", "meaning": "笔记本", "phonetic": "/ˈnəʊtbʊk/", "example": "Write in your notebook.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "pen", "meaning": "钢笔", "phonetic": "/pen/", "example": "Can I borrow your pen?", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "red", "meaning": "红色", "phonetic": "/red/", "example": "The apple is red.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "school", "meaning": "学校", "phonetic": "/skuːl/", "example": "I go to school every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "teacher", "meaning": "老师", "phonetic": "/ˈtiːtʃər/", "example": "My teacher is nice.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "under", "meaning": "在...下面", "phonetic": "/ˈʌndər/", "example": "The cat is under the table.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "window", "meaning": "窗户", "phonetic": "/ˈwɪndəʊ/", "example": "Open the window, please.", "level": 1, "frequency": 4, "difficulty": 1},
    {"word": "beautiful", "meaning": "美丽的", "phonetic": "/ˈbjuːtɪfl/", "example": "What a beautiful flower!", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "computer", "meaning": "电脑", "phonetic": "/kəmˈpjuːtər/", "example": "I use computer every day.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "different", "meaning": "不同的", "phonetic": "/ˈdɪfrənt/", "example": "They have different ideas.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "education", "meaning": "教育", "phonetic": "/ˌedʒuˈkeɪʃn/", "example": "Education is very important.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "favorite", "meaning": "最喜欢的", "phonetic": "/ˈfeɪvərɪt/", "example": "What is your favorite color?", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "government", "meaning": "政府", "phonetic": "/ˈɡʌvənmənt/", "example": "The government helps people.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "hospital", "meaning": "医院", "phonetic": "/ˈhɒspɪtl/", "example": "She works in a hospital.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "important", "meaning": "重要的", "phonetic": "/ɪmˈpɔːtənt/", "example": "This is very important.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "journey", "meaning": "旅程", "phonetic": "/ˈdʒɜːni/", "example": "Have a good journey!", "level": 2, "frequency": 3, "difficulty": 2},
    {"word": "knowledge", "meaning": "知识", "phonetic": "/ˈnɒlɪdʒ/", "example": "Knowledge is power.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "language", "meaning": "语言", "phonetic": "/ˈlæŋɡwɪdʒ/", "example": "English is a global language.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "mountain", "meaning": "山", "phonetic": "/ˈmaʊntən/", "example": "The mountain is very high.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "natural", "meaning": "自然的", "phonetic": "/ˈnætʃrəl/", "example": "This is a natural park.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "opportunity", "meaning": "机会", "phonetic": "/ˌɒpəˈtjuːnəti/", "example": "This is a good opportunity.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "population", "meaning": "人口", "phonetic": "/ˌpɒpjuˈleɪʃn/", "example": "The population is growing.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "question", "meaning": "问题", "phonetic": "/ˈkwestʃən/", "example": "I have a question.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "remember", "meaning": "记得", "phonetic": "/rɪˈmembər/", "example": "Please remember this.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "science", "meaning": "科学", "phonetic": "/ˈsaɪəns/", "example": "Science is interesting.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "technology", "meaning": "技术", "phonetic": "/tekˈnɒlədʒi/", "example": "Technology changes our life.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "understand", "meaning": "理解", "phonetic": "/ˌʌndəˈstænd/", "example": "I understand what you mean.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "weather", "meaning": "天气", "phonetic": "/ˈweðər/", "example": "The weather is nice today.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "family", "meaning": "家庭", "phonetic": "/ˈfæməli/", "example": "I love my family.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "friend", "meaning": "朋友", "phonetic": "/frend/", "example": "She is my best friend.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "school", "meaning": "学校", "phonetic": "/skuːl/", "example": "Our school is big.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "student", "meaning": "学生", "phonetic": "/ˈstjuːdnt/", "example": "I am a student.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "teacher", "meaning": "老师", "phonetic": "/ˈtiːtʃər/", "example": "Our teacher is kind.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "classroom", "meaning": "教室", "phonetic": "/ˈklɑːsruːm/", "example": "The classroom is clean.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "homework", "meaning": "作业", "phonetic": "/ˈhəʊmwɜːk/", "example": "I have a lot of homework.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "exam", "meaning": "考试", "phonetic": "/ɪɡˈzæm/", "example": "I passed the exam.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "grade", "meaning": "年级", "phonetic": "/ɡreɪd/", "example": "I am in grade 8.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "subject", "meaning": "科目", "phonetic": "/ˈsʌbdʒɪkt/", "example": "My favorite subject is math.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "sports", "meaning": "运动", "phonetic": "/spɔːts/", "example": "I like sports.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "music", "meaning": "音乐", "phonetic": "/ˈmjuːzɪk/", "example": "Music makes me happy.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "art", "meaning": "艺术", "phonetic": "/ɑːt/", "example": "I enjoy art class.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "history", "meaning": "历史", "phonetic": "/ˈhɪstri/", "example": "History is interesting.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "geography", "meaning": "地理", "phonetic": "/dʒiˈɒɡrəfi/", "example": "Geography helps us understand the world.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "biology", "meaning": "生物", "phonetic": "/baɪˈɒlədʒi/", "example": "Biology studies living things.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "chemistry", "meaning": "化学", "phonetic": "/ˈkemɪstri/", "example": "Chemistry is fun.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "physics", "meaning": "物理", "phonetic": "/ˈfɪzɪks/", "example": "Physics explains how things work.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "math", "meaning": "数学", "phonetic": "/mæθ/", "example": "Math is challenging.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "science", "meaning": "科学", "phonetic": "/ˈsaɪəns/", "example": "Science explores the world.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "history", "meaning": "历史", "phonetic": "/ˈhɪstri/", "example": "History teaches us about the past.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "geography", "meaning": "地理", "phonetic": "/dʒiˈɒɡrəfi/", "example": "Geography studies the Earth.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "chemistry", "meaning": "化学", "phonetic": "/ˈkemɪstri/", "example": "Chemistry studies matter.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "biology", "meaning": "生物", "phonetic": "/baɪˈɒlədʒi/", "example": "Biology studies living organisms.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "technology", "meaning": "技术", "phonetic": "/tekˈnɒlədʒi/", "example": "Technology changes our lives.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "computer", "meaning": "电脑", "phonetic": "/kəmˈpjuːtər/", "example": "I use a computer for work.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "internet", "meaning": "互联网", "phonetic": "/ˈɪntənet/", "example": "The internet connects people.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "software", "meaning": "软件", "phonetic": "/ˈsɒftweər/", "example": "This software is very useful.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "hardware", "meaning": "硬件", "phonetic": "/ˈhɑːdweər/", "example": "The hardware needs to be upgraded.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "programming", "meaning": "编程", "phonetic": "/ˈprəʊɡræmɪŋ/", "example": "Programming creates software.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "database", "meaning": "数据库", "phonetic": "/ˈdeɪtəbeɪs/", "example": "The database stores information.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "network", "meaning": "网络", "phonetic": "/ˈnetwɜːk/", "example": "The network connects devices.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "communication", "meaning": "交流", "phonetic": "/kəˌmjuːnɪˈkeɪʃn/", "example": "Good communication is important.", "level": 2, "frequency": 4, "difficulty": 3},
    {"word": "information", "meaning": "信息", "phonetic": "/ˌɪnfəˈmeɪʃn/", "example": "Information is power.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "knowledge", "meaning": "知识", "phonetic": "/ˈnɒlɪdʒ/", "example": "Knowledge comes from learning.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "education", "meaning": "教育", "phonetic": "/ˌedʒuˈkeɪʃn/", "example": "Education is the key to success.", "level": 2, "frequency": 4, "difficulty": 3},
    {"word": "learning", "meaning": "学习", "phonetic": "/ˈlɜːnɪŋ/", "example": "Learning is a lifelong process.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "english", "meaning": "英语", "phonetic": "/ˈɪŋɡlɪʃ/", "example": "English is important.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "china", "meaning": "中国", "phonetic": "/ˈtʃaɪnə/", "example": "China is a great country.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "world", "meaning": "世界", "phonetic": "/wɜːld/", "example": "The world is big.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "time", "meaning": "时间", "phonetic": "/taɪm/", "example": "Time flies.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "day", "meaning": "天", "phonetic": "/deɪ/", "example": "Have a nice day!", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "year", "meaning": "年", "phonetic": "/jɪər/", "example": "Happy New Year!", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "month", "meaning": "月", "phonetic": "/mʌnθ/", "example": "There are 12 months in a year.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "week", "meaning": "周", "phonetic": "/wiːk/", "example": "I work five days a week.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "achievement", "meaning": "成就", "phonetic": "/əˈtʃiːvmənt/", "example": "This is a great achievement.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "benefit", "meaning": "益处", "phonetic": "/ˈbenɪfɪt/", "example": "This has many benefits.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "consequence", "meaning": "后果", "phonetic": "/ˈkɒnsɪkwəns/", "example": "Think about the consequences.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "demonstrate", "meaning": "展示", "phonetic": "/ˈdemənstreɪt/", "example": "Let me demonstrate this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "environment", "meaning": "环境", "phonetic": "/ɪnˈvaɪrənmənt/", "example": "We should protect the environment.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "fundamental", "meaning": "基本的", "phonetic": "/ˌfʌndəˈmentl/", "example": "This is a fundamental principle.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "generation", "meaning": "一代", "phonetic": "/ˌdʒenəˈreɪʃn/", "example": "This is a new generation.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "hypothesis", "meaning": "假设", "phonetic": "/haɪˈpɒθəsɪs/", "example": "This is just a hypothesis.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "imagination", "meaning": "想象力", "phonetic": "/ɪˌmædʒɪˈneɪʃn/", "example": "Use your imagination.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "journalism", "meaning": "新闻业", "phonetic": "/ˈdʒɜːnəlɪzəm/", "example": "He works in journalism.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "legislation", "meaning": "立法", "phonetic": "/ˌledʒɪsˈleɪʃn/", "example": "New legislation was passed.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "magnificent", "meaning": "壮丽的", "phonetic": "/mæɡˈnɪfɪsnt/", "example": "What a magnificent view!", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "negotiation", "meaning": "谈判", "phonetic": "/nɪˌɡəʊʃiˈeɪʃn/", "example": "The negotiation was successful.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "phenomenon", "meaning": "现象", "phonetic": "/fɪˈnɒmɪnən/", "example": "This is a natural phenomenon.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "psychological", "meaning": "心理的", "phonetic": "/ˌsaɪkəˈlɒdʒɪkl/", "example": "This has psychological effects.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "representative", "meaning": "代表", "phonetic": "/ˌreprɪˈzentətɪv/", "example": "He is a representative.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "significant", "meaning": "重要的", "phonetic": "/sɪɡˈnɪfɪkənt/", "example": "This is a significant discovery.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "temperature", "meaning": "温度", "phonetic": "/ˈtemprətʃə/", "example": "The temperature is rising.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "unanimous", "meaning": "一致的", "phonetic": "/juˈnænɪməs/", "example": "The decision was unanimous.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "vulnerable", "meaning": "脆弱的", "phonetic": "/ˈvʌlnərəbl/", "example": "Children are vulnerable.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "yield", "meaning": "产出", "phonetic": "/jiːld/", "example": "This field yields good crops.", "level": 3, "frequency": 2, "difficulty": 3},
    {"word": "academic", "meaning": "学术的", "phonetic": "/ˌækəˈdemɪk/", "example": "This is an academic paper.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "analyze", "meaning": "分析", "phonetic": "/ˈænəlaɪz/", "example": "Let me analyze this data.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "conclusion", "meaning": "结论", "phonetic": "/kənˈkluːʒn/", "example": "What is your conclusion?", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "contribution", "meaning": "贡献", "phonetic": "/ˌkɒntrɪˈbjuːʃn/", "example": "Thank you for your contribution.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "dependence", "meaning": "依赖", "phonetic": "/dɪˈpendəns/", "example": "Independence is important.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "evidence", "meaning": "证据", "phonetic": "/ˈevɪdəns/", "example": "Show me the evidence.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "influence", "meaning": "影响", "phonetic": "/ˈɪnfluəns/", "example": "Music has a big influence on me.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "investigate", "meaning": "调查", "phonetic": "/ɪnˈvestɪɡeɪt/", "example": "We need to investigate this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "justify", "meaning": "证明", "phonetic": "/ˈdʒʌstɪfaɪ/", "example": "Can you justify your decision?", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "literature", "meaning": "文学", "phonetic": "/ˈlɪtrətʃə/", "example": "I enjoy reading literature.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "mechanism", "meaning": "机制", "phonetic": "/ˈmekənɪzəm/", "example": "How does this mechanism work?", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "perspective", "meaning": "视角", "phonetic": "/pəˈspektɪv/", "example": "Try a different perspective.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "principle", "meaning": "原则", "phonetic": "/ˈprɪnsɪpl/", "example": "This is a basic principle.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "research", "meaning": "研究", "phonetic": "/rɪˈsɜːtʃ/", "example": "She is doing research.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "strategy", "meaning": "策略", "phonetic": "/ˈstrætədʒi/", "example": "What is your strategy?", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "theory", "meaning": "理论", "phonetic": "/ˈθɪəri/", "example": "This is just a theory.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "approach", "meaning": "方法", "phonetic": "/əˈprəʊtʃ/", "example": "This is a good approach.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "assumption", "meaning": "假设", "phonetic": "/əˈsʌmpʃn/", "example": "This assumption may be wrong.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "circumstance", "meaning": "情况", "phonetic": "/ˈsɜːkəmstəns/", "example": "Under these circumstances.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "distinction", "meaning": "区别", "phonetic": "/dɪˈstɪŋkʃn/", "example": "There is a clear distinction.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "emphasis", "meaning": "强调", "phonetic": "/ˈemfəsɪs/", "example": "The emphasis is on quality.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "guarantee", "meaning": "保证", "phonetic": "/ˌɡærənˈtiː/", "example": "I guarantee this will work.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "implication", "meaning": "暗示", "phonetic": "/ˌɪmplɪˈkeɪʃn/", "example": "What are the implications?", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "limitation", "meaning": "限制", "phonetic": "/ˌlɪmɪˈteɪʃn/", "example": "Every method has limitations.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "preference", "meaning": "偏好", "phonetic": "/ˈprefrəns/", "example": "This is my personal preference.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "reference", "meaning": "参考", "phonetic": "/ˈrefrəns/", "example": "Please check the references.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "responsibility", "meaning": "责任", "phonetic": "/rɪˌspɒnsəˈbɪləti/", "example": "This is your responsibility.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "solution", "meaning": "解决方案", "phonetic": "/səˈluːʃn/", "example": "We need a solution.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "tendency", "meaning": "倾向", "phonetic": "/ˈtendənsi/", "example": "There is a tendency to agree.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "validity", "meaning": "有效性", "phonetic": "/vəˈlɪdəti/", "example": "We need to check the validity.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "access", "meaning": "访问", "phonetic": "/ˈækses/", "example": "You have access to this.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "acquire", "meaning": "获得", "phonetic": "/əˈkwaɪə/", "example": "We need to acquire more data.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "adapt", "meaning": "适应", "phonetic": "/əˈdæpt/", "example": "We need to adapt to changes.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "affect", "meaning": "影响", "phonetic": "/əˈfekt/", "example": "This will affect our decision.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "alter", "meaning": "改变", "phonetic": "/ˈɔːltər/", "example": "We need to alter our plan.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "compose", "meaning": "组成", "phonetic": "/kəmˈpəʊz/", "example": "Water is composed of hydrogen and oxygen.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "derive", "meaning": "推导", "phonetic": "/dɪˈraɪv/", "example": "We can derive this formula.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "differentiate", "meaning": "区分", "phonetic": "/ˌdɪfəˈrenʃieɪt/", "example": "Can you differentiate between them?", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "elaborate", "meaning": "详细说明", "phonetic": "/ɪˈlæbərət/", "example": "Please elaborate on this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "facilitate", "meaning": "促进", "phonetic": "/fəˈsɪlɪteɪt/", "example": "This will facilitate our work.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "generate", "meaning": "生成", "phonetic": "/ˈdʒenəreɪt/", "example": "This will generate new ideas.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "identify", "meaning": "识别", "phonetic": "/aɪˈdentɪfaɪ/", "example": "We need to identify the problem.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "maintain", "meaning": "维持", "phonetic": "/meɪnˈteɪn/", "example": "We need to maintain quality.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "obtain", "meaning": "获得", "phonetic": "/əbˈteɪn/", "example": "We need to obtain permission.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "predict", "meaning": "预测", "phonetic": "/prɪˈdɪkt/", "example": "It is hard to predict the future.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "propose", "meaning": "提议", "phonetic": "/prəˈpəʊz/", "example": "I propose a new idea.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "regulate", "meaning": "规范", "phonetic": "/ˈreɡjuleɪt/", "example": "We need to regulate this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "resemble", "meaning": "类似", "phonetic": "/rɪˈzembəl/", "example": "You resemble your mother.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "reveal", "meaning": "揭示", "phonetic": "/rɪˈviːl/", "example": "This reveals the truth.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "substitute", "meaning": "替代", "phonetic": "/ˈsʌbstɪtjuːt/", "example": "We can substitute this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "transform", "meaning": "转变", "phonetic": "/trænsˈfɔːm/", "example": "This will transform our approach.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "utilize", "meaning": "利用", "phonetic": "/ˈjuːtɪlaɪz/", "example": "We need to utilize this resource.", "level": 3, "frequency": 3, "difficulty": 3}
]

def init_sample_data(db_session):
    from models.vocabulary import Vocabulary
    for word in SAMPLE_WORDS:
        existing = db_session.query(Vocabulary).filter_by(word=word['word']).first()
        if not existing:
            vocab = Vocabulary(**word)
            db_session.add(vocab)
    db_session.commit()
