SAMPLE_WORDS = [
    {"word": "apple", "meaning": "苹果", "phonetic": "/ˈæpl/", "example": "I eat an apple every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "book", "meaning": "书", "phonetic": "/bʊk/", "example": "This is a good book.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "cat", "meaning": "猫", "phonetic": "/kæt/", "example": "The cat is sleeping.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "dog", "meaning": "狗", "phonetic": "/dɒɡ/", "example": "I have a pet dog.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "egg", "meaning": "鸡蛋", "phonetic": "/eɡ/", "example": "I had an egg for breakfast.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "fish", "meaning": "鱼", "phonetic": "/fɪʃ/", "example": "The fish swims in water.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "girl", "meaning": "女孩", "phonetic": "/ɡɜːl/", "example": "She is a happy girl.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "hand", "meaning": "手", "phonetic": "/hænd/", "example": "Wash your hands before eating.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "ice", "meaning": "冰", "phonetic": "/aɪs/", "example": "The ice is cold.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "jump", "meaning": "跳", "phonetic": "/dʒʌmp/", "example": "The rabbit can jump high.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "kind", "meaning": "友善的", "phonetic": "/kaɪnd/", "example": "She is a kind person.", "level": 1, "frequency": 4, "difficulty": 2},
    {"word": "love", "meaning": "爱", "phonetic": "/lʌv/", "example": "I love my family.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "milk", "meaning": "牛奶", "phonetic": "/mɪlk/", "example": "Drink milk every day.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "name", "meaning": "名字", "phonetic": "/neɪm/", "example": "What is your name?", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "orange", "meaning": "橙子", "phonetic": "/ˈɒrɪndʒ/", "example": "The orange is sweet.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "play", "meaning": "玩", "phonetic": "/pleɪ/", "example": "Children like to play.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "queen", "meaning": "女王", "phonetic": "/kwiːn/", "example": "The queen lives in a castle.", "level": 1, "frequency": 3, "difficulty": 2},
    {"word": "rain", "meaning": "雨", "phonetic": "/reɪn/", "example": "It is raining outside.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "sun", "meaning": "太阳", "phonetic": "/sʌn/", "example": "The sun is shining.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "tree", "meaning": "树", "phonetic": "/triː/", "example": "The tree is tall.", "level": 1, "frequency": 5, "difficulty": 1},
    {"word": "beautiful", "meaning": "美丽的", "phonetic": "/ˈbjuːtɪfl/", "example": "What a beautiful flower!", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "computer", "meaning": "电脑", "phonetic": "/kəmˈpjuːtər/", "example": "I use computer every day.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "different", "meaning": "不同的", "phonetic": "/ˈdɪfrənt/", "example": "They have different ideas.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "education", "meaning": "教育", "phonetic": "/ˌedʒuˈkeɪʃn/", "example": "Education is very important.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "favorite", "meaning": "最喜欢的", "phonetic": "/ˈfeɪvərɪt/", "example": "What is your favorite color?", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "government", "meaning": "政府", "phonetic": "/ˈɡʌvənmənt/", "example": "The government helps people.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "hospital", "meaning": "医院", "phonetic": "/ˈhɒspɪtl/", "example": "She works in a hospital.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "important", "meaning": "重要的", "phonetic": "/ɪmˈpɔːtənt/", "example": "This is very important.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "journey", "meaning": "旅程", "phonetic": "/ˈdʒɜːni/", "example": "Have a good journey!", "level": 2, "frequency": 3, "difficulty": 2},
    {"word": "knowledge", "meaning": "知识", "phonetic": "/ˈnɒlɪdʒ/", "example": "Knowledge is power.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "language", "meaning": "语言", "phonetic": "/ˈlæŋɡwɪdʒ/", "example": "English is a global language.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "mountain", "meaning": "山", "phonetic": "/ˈmaʊntən/", "example": "The mountain is very high.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "natural", "meaning": "自然的", "phonetic": "/ˈnætʃrəl/", "example": "This is a natural park.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "opportunity", "meaning": "机会", "phonetic": "/ˌɒpəˈtjuːnəti/", "example": "This is a good opportunity.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "population", "meaning": "人口", "phonetic": "/ˌpɒpjuˈleɪʃn/", "example": "The population is growing.", "level": 2, "frequency": 3, "difficulty": 3},
    {"word": "question", "meaning": "问题", "phonetic": "/ˈkwestʃən/", "example": "I have a question.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "remember", "meaning": "记得", "phonetic": "/rɪˈmembər/", "example": "Please remember this.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "science", "meaning": "科学", "phonetic": "/ˈsaɪəns/", "example": "Science is interesting.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "technology", "meaning": "技术", "phonetic": "/tekˈnɒlədʒi/", "example": "Technology changes our life.", "level": 2, "frequency": 4, "difficulty": 2},
    {"word": "understand", "meaning": "理解", "phonetic": "/ˌʌndəˈstænd/", "example": "I understand what you mean.", "level": 2, "frequency": 5, "difficulty": 2},
    {"word": "achievement", "meaning": "成就", "phonetic": "/əˈtʃiːvmənt/", "example": "This is a great achievement.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "benefit", "meaning": "益处", "phonetic": "/ˈbenɪfɪt/", "example": "This has many benefits.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "consequence", "meaning": "后果", "phonetic": "/ˈkɒnsɪkwəns/", "example": "Think about the consequences.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "demonstrate", "meaning": "展示", "phonetic": "/ˈdemənstreɪt/", "example": "Let me demonstrate this.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "environment", "meaning": "环境", "phonetic": "/ɪnˈvaɪrənmənt/", "example": "We should protect the environment.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "fundamental", "meaning": "基本的", "phonetic": "/ˌfʌndəˈmentl/", "example": "This is a fundamental principle.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "generation", "meaning": "一代", "phonetic": "/ˌdʒenəˈreɪʃn/", "example": "This is a new generation.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "hypothesis", "meaning": "假设", "phonetic": "/haɪˈpɒθəsɪs/", "example": "This is just a hypothesis.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "imagination", "meaning": "想象力", "phonetic": "/ɪˌmædʒɪˈneɪʃn/", "example": "Use your imagination.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "journalism", "meaning": "新闻业", "phonetic": "/ˈdʒɜːnəlɪzəm/", "example": "He works in journalism.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "legislation", "meaning": "立法", "phonetic": "/ˌledʒɪsˈleɪʃn/", "example": "New legislation was passed.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "magnificent", "meaning": "壮丽的", "phonetic": "/mæɡˈnɪfɪsnt/", "example": "What a magnificent view!", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "negotiation", "meaning": "谈判", "phonetic": "/nɪˌɡəʊʃiˈeɪʃn/", "example": "The negotiation was successful.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "phenomenon", "meaning": "现象", "phonetic": "/fɪˈnɒmɪnən/", "example": "This is a natural phenomenon.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "psychological", "meaning": "心理的", "phonetic": "/ˌsaɪkəˈlɒdʒɪkl/", "example": "This has psychological effects.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "representative", "meaning": "代表", "phonetic": "/ˌreprɪˈzentətɪv/", "example": "He is a representative.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "significant", "meaning": "重要的", "phonetic": "/sɪɡˈnɪfɪkənt/", "example": "This is a significant discovery.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "temperature", "meaning": "温度", "phonetic": "/ˈtemprətʃə/", "example": "The temperature is rising.", "level": 3, "frequency": 3, "difficulty": 3},
    {"word": "unanimous", "meaning": "一致的", "phonetic": "/juˈnænɪməs/", "example": "The decision was unanimous.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "vulnerable", "meaning": "脆弱的", "phonetic": "/ˈvʌlnərəbl/", "example": "Children are vulnerable.", "level": 3, "frequency": 2, "difficulty": 4},
    {"word": "yield", "meaning": "产出", "phonetic": "/jiːld/", "example": "This field yields good crops.", "level": 3, "frequency": 2, "difficulty": 3}
]

def init_sample_data(db_session):
    from models.vocabulary import Vocabulary
    for word in SAMPLE_WORDS:
        existing = db_session.query(Vocabulary).filter_by(word=word['word']).first()
        if not existing:
            vocab = Vocabulary(**word)
            db_session.add(vocab)
    db_session.commit()